--Presentar un cursos que imprima el primer registro de la tabla AEREOLINEA
--VISUALIZAR LA TABLA AEROLINEA
SELECT * FROM AEROLINEA
GO
--CREACION Y CONFIGURACION DEL CURSOR
DECLARE CUR_TBL_AEROLINEA CURSOR
FOR SELECT * FROM AEROLINEA

OPEN CUR_TBL_AEROLINEA
FETCH NEXT FROM CUR_TBL_AEROLINEA
CLOSE CUR_TBL_AEROLINEA
DEALLOCATE CUR_TBL_AEROLINEA


FETCH NEXT FROM CUR_TBL_AEROLINEA